### ISSUE TITLE
Server wont stop after stop command

### ISSUE THREAD

**Issue by dterweij** [Hydreon/Steadfast2#113]
OS Linux CentOS 6
PHP 7.0.8

Issue a stop command:
```
[06:30:26] [Server thread/INFO]: Unloading level "world"
[06:30:26] [Server thread/INFO]: Stopping other threads
[06:30:26] [Server thread/CRITICAL]: Error: "Call to undefined method pocketmine\command\CommandReader::unstack()" (EXCEPTION) in "/src/pocketmine/Thread" at line 79
```

Then it waits forever, no return to the commandprompt.

**Comment by dterweij** [comment]
I need it fixed. I need the exit code. Or build in a PID run file on linux so i can kill it from another (master) script. (Just wonder why there is no PID file created for all Pocketmine servers that are on linux.... it is so easy to implement and makes life easier for linux admins.).

Because it does not stop after stop command, this is happening here:

```
# ps ax | grep Stead
 307455 ?        Sl     12:03 PocketMine-Steadfast 1.5.1-hybrid                  
 357514 ?        Sl     8:25 PocketMine-Steadfast 1.5.1-hybrid                  
 28414 ?        Sl     3:33 PocketMine-Steadfast 1.5.1-hybrid                  
 16534 ?        Sl     1:07 PocketMine-Steadfast 1.5.1-hybrid                  
 127635 ?        Sl     1:00 PocketMine-Steadfast 1.5.1-hybrid 
```                 

And that is eating up system resources.

**Comment by DavidJBrockway** [comment]
We are fixing this

**Comment by thebigsmileXD** [comment]
@DavidJBrockway we did go back to an old version of CommandReader, then it was fixed.

**Comment by thebigsmileXD** [comment]
@dterweij you may concider using a different fork meanwhile then.

**Comment by williamtdr** [comment]
@dterweij It should stop by itself, the threads are probably from plugins that aren't cleaning up their resources properly before closing. It's pretty easy to make your own PID file in a plugin on startup, and I'd recommend doing so. Steadfast is meant to be used alongside custom helper plugins, and you'll have to come up with management features yourself.

**Comment by dterweij** [comment]
@williamtdr 

`[Server thread/CRITICAL]: Error: "Call to undefined method pocketmine\command\CommandReader::unstack()" (EXCEPTION) in "/src/pocketmine/Thread" at line 79`

Still happens.  
The only plugin is devtools.  Its used to build the phar only. Because it is not responding, the build system like Jenkins is stuck. I had to install a inactivity timer to cancel the job but the build is still running as process. I lowered the builds to just once a week so I have to just manualy kill Steadfast once a week. 

Steadfast only has this problem. All other clones not.

I tried make a PID, but it is the PID from the build job. Not the PID from Steadfast. If I want the real Steadfast PID then Steadfast should make a PID :)

Keep the issue open, it is really a big problem that has to be solved.

**Comment by dterweij** [comment]
You might just update the Threads.php to the lastest version ?

https://github.com/PocketMine/PocketMine-MP/blob/master/src/pocketmine/Thread.php

All clones using this one......

**Comment by thebigsmileXD** [comment]
* https://github.com/pmmp/PocketMine-MP/blob/master/src/pocketmine/Thread.php

Btter keeping the latest
